version: 2
jobs:
  build:
    docker:
      - image: daedalus2718/libri-build
    parallelism: 1
    working_directory: /go/src/github.com/elxirhealth/service-base
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}
      - run: make get-deps
      - save_cache:
          key: v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make build
      - run: make test
      - run: make lint
