version: 2
jobs:
  build:
    docker:
      - image: gcr.io/elxir-core-infra/service-base-build:latest
        auth:
          username: _json_key
          password: ${GCR_SVC_JSON}
    parallelism: 1
    working_directory: /go/src/github.com/elixirhealth/service-base
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}
      - run: make get-deps
      - save_cache:
          key: v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make build
      - run: make test
      - run: make lint
