// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/base/server/test/pingpong.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	pkg/base/server/test/pingpong.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Ping bool `protobuf:"varint,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetPing() bool {
	if m != nil {
		return m.Ping
	}
	return false
}

type PingResponse struct {
	Pong bool `protobuf:"varint,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetPong() bool {
	if m != nil {
		return m.Pong
	}
	return false
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "test.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "test.PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingPong service

type PingPongClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/test.PingPong/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingPong service

type PingPongServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.PingPong/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingPong_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/base/server/test/pingpong.proto",
}

func init() { proto.RegisterFile("pkg/base/server/test/pingpong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xb1, 0x0a, 0x02, 0x31,
	0x0c, 0x06, 0x60, 0x0f, 0x0e, 0x39, 0xa2, 0x8b, 0x99, 0xc4, 0x49, 0xeb, 0xe2, 0xd4, 0x82, 0x8e,
	0xbe, 0xc4, 0x71, 0x6f, 0xe0, 0x41, 0x08, 0x87, 0x90, 0xd4, 0xa6, 0xfa, 0xfc, 0xd2, 0xde, 0xd2,
	0xed, 0xe7, 0xe7, 0xe3, 0x4f, 0xe0, 0x1a, 0xdf, 0x1c, 0xe6, 0x97, 0x51, 0x30, 0x4a, 0x3f, 0x4a,
	0x21, 0x93, 0xe5, 0x10, 0x17, 0xe1, 0xa8, 0xc2, 0x3e, 0x26, 0xcd, 0x8a, 0x7d, 0x29, 0xdd, 0x05,
	0x76, 0xe3, 0x22, 0x3c, 0xd1, 0xe7, 0x4b, 0x96, 0x11, 0xa1, 0x2f, 0xec, 0xd8, 0x9d, 0xbb, 0xdb,
	0x30, 0xd5, 0xec, 0x1c, 0xec, 0x57, 0x62, 0x51, 0xc5, 0xa8, 0x1a, 0x6d, 0x8c, 0x0a, 0xdf, 0x9f,
	0x30, 0x14, 0x33, 0xaa, 0x30, 0x06, 0xe8, 0x4b, 0xc6, 0x83, 0x2f, 0x17, 0x7c, 0x33, 0x7f, 0xc2,
	0xb6, 0x5a, 0xe7, 0xdc, 0x66, 0xde, 0xd6, 0x87, 0x1e, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda,
	0xa4, 0xdd, 0xd3, 0xb7, 0x00, 0x00, 0x00,
}
